language:
  - ruby
  - node_js

install:
  - bundle install
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _site
  on:
    branch: gh-pages-test

# blocklist
branches:
  except:
  - gh-pages
