language:
  - ruby
  - node_js

install:
  - bundle install
  - npm install

script:
  - npm run build

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: _site
    target-branch: gh-pages-test 
    on:
      branch: master

# blocklist
branches:
  except:
  - gh-pages
